version: '3'
services:
  server:
    image: finncloudcomp/microservice:server
    ports:
      - "3000:3000"
    depends_on:
      - hello-world-service
      - product-descp-service
      - product-price-service
  hello-world-service:
    image: finncloudcomp/microservice:hello
  product-descp-service:
    image: finncloudcomp/microservice:productdescp
  product-price-service:
    image: finncloudcomp/microservice:productprice

